sudo: false

language: node_js

os:
  - linux
  - osx

node_js:
  - 6.5.0

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - icnsutils
      - graphicsmagick
      - xz-utils
      - xorriso

install:
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run coveralls
  - npm run build
  - npm run package
