sudo: false
language: node_js
os:
- linux
- osx
node_js:
- 6
cache:
  directories:
  - node_modules
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - icnsutils
    - graphicsmagick
    - xz-utils
    - xorriso
matrix:
  include:
    - os: linux
      env: DEPLOY_PACKAGE=release/linux
    - os: osx
      osx_image: xcode8.2
      env: DEPLOY_PACKAGE=release/osx
install:
- if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then export CXX="g++-4.8"; fi
- npm install -g npm@latest
- npm install
script:
- npm run lint
- npm run test
- npm run package
- ls release
after_success: if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then npm run coverage; fi
deploy:
  provider: releases
  api_key:
    secure: h37ydCUTlcJKKEyi3q1xeYHvcgir0y7A0soc9a2LaE3fIqeX9bgyhtjhhjHNdXJEDm2n7yrhvifek58xJecoywzJQgngEpjiyDqCeFZY6dfneVpzHm/0JIQRhud40UjE4XlvlZ5mhTqXjW8KtkD3fiU/GPS6vKZSuQR4MjDN2QUO6KsEaDHKKI26xgXZ7b4k+YGROrhX7FgdVQ95zviI5jrB3qHrQd1yNcLL/ut6jRTWdSYG+++DYVR1WR9mIR9ZkvPIH1o6ZgGmLe60r6lG4giDIswrghJzuYB1s1Z6yTEwwhii0G2N0OItSsRA1J8XnJssKN4Ha0/4z7JeLo6nNnkS70jwdmkjRTQB3A9JqxsXGELF/8T8rBhu5fWVxuSxLkXSTai5YZoaQwMrPDwCPD7AtWPxAQdSn5Pu7n5LqunQe6m56A8fb9o3RvNkKqVn+Jlmebe16VQCSlJdXmxPVIFpWPdJZY6Rwyk8GgCrrmVEKu7hG0TEKzZGFj6D2gIB97iZtWZjqSKFuzK3dyHDMMFCwbDbCyGpCnoUo6ttFerEGLhiOUGIim4v0YeERbG2njWUP5Qh8rU8Qzp7WF8l5fgLo3x3fgeoAEFzn6TSHgpEb/uJwhTwCdBeU10fO+YRbckEJvsHuo7m0UgSE9S5N/25YQPhtfYyoDbr0X2jCFU=
  file: $DEPLOY_PACKAGE
  skip_cleanup: true
  on:
    repo: hunterjm/fifa-autobuyer
    tags: true
